-- MySQL Script generated by MySQL Workbench
-- Tue May 14 11:10:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS DietBaseDB;
CREATE DATABASE IF NOT EXISTS DietBaseDB;
USE DietBaseDB;
SET sql_notes = 0;
-- -----------------------------------------------------
-- Table `Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Users` ;

CREATE TABLE IF NOT EXISTS `Users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` CHAR(20) NOT NULL,
  `last_name` CHAR(20) NOT NULL,
  `name` CHAR(40) GENERATED ALWAYS AS (CONCAT(first_name, ' ', last_name)) VIRTUAL,
  `email` VARCHAR(30) NOT NULL,
  `password` VARCHAR(15) NULL,
  PRIMARY KEY (`user_id`, `email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Devices` ;

CREATE TABLE IF NOT EXISTS `Devices` (
  `device_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `device_type` VARCHAR(30) NULL,
  `device_name` VARCHAR(30) NULL,
  PRIMARY KEY (`device_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `account_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `dob` DATE NULL,
  `age` TINYINT UNSIGNED NULL,
  `date_joined` DATE NOT NULL,
  PRIMARY KEY (`account_id`, `user_id`, `username`),
  INDEX `PK_USER_ID_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `PK_ACCOUNT_USER`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Allergies and Restrictions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Allergies and Restrictions` ;

CREATE TABLE IF NOT EXISTS `Allergies and Restrictions` (
  `restriction_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restriction_name` VARCHAR(20) NOT NULL,
  `restriction_type` VARCHAR(12) NULL,
  PRIMARY KEY (`restriction_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restriction Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restriction Log` ;

CREATE TABLE IF NOT EXISTS `Restriction Log` (
  `restriction_id` TINYINT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  `severity_level` VARCHAR(10) NOT NULL,
  INDEX `FK_RLOG_RESTRICTIONS_idx` (`restriction_id` ASC) VISIBLE,
  INDEX `FK_RLOG_ACCOUNTS_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `FK_RLOG_RESTRICTIONS`
    FOREIGN KEY (`restriction_id`)
    REFERENCES `Allergies and Restrictions` (`restriction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RLOG_ACCOUNTS`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Login Sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Login Sessions` ;

CREATE TABLE IF NOT EXISTS `Login Sessions` (
  `device_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `login_date` DATETIME NOT NULL,
  `logout_date` DATETIME NULL,
  INDEX `FK_SESSIONS_USER_idx` (`user_id` ASC) VISIBLE,
  INDEX `FK_SESSIONS_DEVICE_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `FK_SESSIONS_USER`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SESSIONS_DEVICE`
    FOREIGN KEY (`device_id`)
    REFERENCES `Devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Time Zones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Time Zones` ;

CREATE TABLE IF NOT EXISTS `Time Zones` (
  `time_zone_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `time_zone_name` VARCHAR(30) NOT NULL,
  `utc_offset` TINYINT NOT NULL,
  PRIMARY KEY (`time_zone_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locations` ;

CREATE TABLE IF NOT EXISTS `Locations` (
  `location_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `location_name` VARCHAR(30) NOT NULL,
  `currency` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Measurement Systems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Measurement Systems` ;

CREATE TABLE IF NOT EXISTS `Measurement Systems` (
  `system_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `system_name` VARCHAR(40) NOT NULL,
  `units` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`system_id`, `system_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Languages` ;

CREATE TABLE IF NOT EXISTS `Languages` (
  `language_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `language_name` VARCHAR(30) NOT NULL,
  `language_code` CHAR(2) NOT NULL,
  PRIMARY KEY (`language_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account Settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account Settings` ;

CREATE TABLE IF NOT EXISTS `Account Settings` (
  `account_id` INT UNSIGNED NOT NULL,
  `time_zone_id` TINYINT UNSIGNED NOT NULL,
  `language_id` TINYINT UNSIGNED NOT NULL,
  `system_id` TINYINT UNSIGNED NOT NULL,
  `location_id` TINYINT UNSIGNED NOT NULL,
  `goal` VARCHAR(20) NOT NULL,
  INDEX `FK_SETTINGS_LANGUAGES_idx` (`language_id` ASC) VISIBLE,
  INDEX `FK_SETTINGS_SYSTEM_idx` (`system_id` ASC) VISIBLE,
  INDEX `FK_SETTINGS_LOCATION_idx` (`location_id` ASC) VISIBLE,
  INDEX `FK_SETTINGS_TIMEZONE_idx` (`time_zone_id` ASC) VISIBLE,
  PRIMARY KEY (`account_id`),
  CONSTRAINT `FK_SETTINGS_LANGUAGES`
    FOREIGN KEY (`language_id`)
    REFERENCES `Languages` (`language_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PK_SETTINGS_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SETTINGS_SYSTEM`
    FOREIGN KEY (`system_id`)
    REFERENCES `Measurement Systems` (`system_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SETTINGS_LOCATION`
    FOREIGN KEY (`location_id`)
    REFERENCES `Locations` (`location_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SETTINGS_TIMEZONE`
    FOREIGN KEY (`time_zone_id`)
    REFERENCES `Time Zones` (`time_zone_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Measurements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Measurements` ;

CREATE TABLE IF NOT EXISTS `Measurements` (
  `account_id` INT UNSIGNED NOT NULL,
  `height` TINYINT UNSIGNED NULL,
  `starting_weight` TINYINT UNSIGNED NULL,
  `gender` VARCHAR(10) NULL,
  PRIMARY KEY (`account_id`),
  CONSTRAINT `PK_MEASUREMENTS_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Long-Term Goals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Long-Term Goals` ;

CREATE TABLE IF NOT EXISTS `Long-Term Goals` (
  `account_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(20) NOT NULL,
  `description` VARCHAR(550) NULL,
  `date_assigned` DATE NOT NULL,
  `complete_by_date` DATE NULL,
  `completed` TINYINT NOT NULL,
  INDEX `FK_LTGOALS_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `FK_LTGOALS_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Nutritional Goals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Nutritional Goals` ;

CREATE TABLE IF NOT EXISTS `Nutritional Goals` (
  `account_id` INT UNSIGNED NOT NULL,
  `calories` SMALLINT UNSIGNED NULL,
  `micro_nutrients` VARCHAR(500) NULL,
  `protein` SMALLINT UNSIGNED NULL,
  `carbs` SMALLINT UNSIGNED NULL,
  `fats` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`account_id`),
  CONSTRAINT `PK_NUTGOALS_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Weight Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Weight Log` ;

CREATE TABLE IF NOT EXISTS `Weight Log` (
  `account_id` INT UNSIGNED NOT NULL,
  `weight` TINYINT UNSIGNED NOT NULL,
  `weight_log_date` DATE NOT NULL,
  INDEX `FK_WEIGHTLOG_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `FK_WEIGHTLOG_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fasting Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fasting Log` ;

CREATE TABLE IF NOT EXISTS `Fasting Log` (
  `account_id` INT UNSIGNED NOT NULL,
  `time_length` SMALLINT UNSIGNED NOT NULL,
  `fasting_date` DATETIME NOT NULL,
  INDEX `FK_FASTING_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `FK_FASTING_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Water Intake`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Water Intake` ;

CREATE TABLE IF NOT EXISTS `Water Intake` (
  `account_id` INT UNSIGNED NOT NULL,
  `water_amount` SMALLINT UNSIGNED NOT NULL,
  `water_intake_date` DATETIME NOT NULL,
  INDEX `FK_WATER_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `FK_WATER_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Step Counter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Step Counter` ;

CREATE TABLE IF NOT EXISTS `Step Counter` (
  `account_id` INT UNSIGNED NOT NULL,
  `step_amount` INT UNSIGNED NOT NULL,
  `step_counter_date` DATE NOT NULL,
  INDEX `FK_STEPCOUNT_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `FK_STEPCOUNT_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sleep Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sleep Log` ;

CREATE TABLE IF NOT EXISTS `Sleep Log` (
  `account_id` INT UNSIGNED NOT NULL,
  `sleep_amount` SMALLINT NOT NULL,
  `sleep_date` DATE NOT NULL,
  INDEX `FK_SLEEP_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `FK_SLEEP_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Nutritional Information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Nutritional Information` ;

CREATE TABLE IF NOT EXISTS `Nutritional Information` (
  `nutrition_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `calories` SMALLINT UNSIGNED NOT NULL,
  `serving_size` VARCHAR(25) NOT NULL,
  `micro_nutrients` VARCHAR(500) NULL,
  `verification` VARCHAR(8) NOT NULL,
  `protein` DECIMAL(4,1) UNSIGNED NULL,
  `carbs` DECIMAL(4,1) UNSIGNED NULL,
  `fats` DECIMAL(4,1) UNSIGNED NULL,
  `barcode` VARCHAR(50) NULL,
  PRIMARY KEY (`nutrition_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Food`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Food` ;

CREATE TABLE IF NOT EXISTS `Food` (
  `food_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `nutrition_id` INT UNSIGNED NULL,
  `brand` VARCHAR(30) NULL,
  PRIMARY KEY (`food_id`),
  UNIQUE INDEX `nutrition_id_UNIQUE` (`nutrition_id` ASC) VISIBLE,
  CONSTRAINT `UQ_FOOD_NUTRITION`
    FOREIGN KEY (`nutrition_id`)
    REFERENCES `Nutritional Information` (`nutrition_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Food Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Food Type` ;

CREATE TABLE IF NOT EXISTS `Food Type` (
  `food_type_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `food_type_name` VARCHAR(20) NOT NULL,
  `food_type_description` VARCHAR(100) NULL,
  PRIMARY KEY (`food_type_id`, `food_type_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assigned Food Types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Assigned Food Types` ;

CREATE TABLE IF NOT EXISTS `Assigned Food Types` (
  `food_id` INT UNSIGNED NOT NULL,
  `food_type_id` SMALLINT UNSIGNED NOT NULL,
  `date_updated` DATE NOT NULL,
  INDEX `FK_ASSIGNEDFT_FOOD_idx` (`food_id` ASC) VISIBLE,
  INDEX `FK_ASSIGNEDFT_FOODTYPE_idx` (`food_type_id` ASC) VISIBLE,
  CONSTRAINT `FK_ASSIGNEDFT_FOOD`
    FOREIGN KEY (`food_id`)
    REFERENCES `Food` (`food_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ASSIGNEDFT_FOODTYPE`
    FOREIGN KEY (`food_type_id`)
    REFERENCES `Food Type` (`food_type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recipe` ;

CREATE TABLE IF NOT EXISTS `Recipe` (
  `recipe_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `nutrition_id` INT UNSIGNED NULL,
  `directions` VARCHAR(1000) NOT NULL,
  `difficulty` TINYINT UNSIGNED NULL,
  INDEX `UQ_RECIPE_NUTRITION_idx` (`nutrition_id` ASC) VISIBLE,
  UNIQUE INDEX `nutrition_id_UNIQUE` (`nutrition_id` ASC) VISIBLE,
  PRIMARY KEY (`recipe_id`),
  CONSTRAINT `UQ_RECIPE_NUTRITION`
    FOREIGN KEY (`nutrition_id`)
    REFERENCES `Nutritional Information` (`nutrition_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Used in Recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Used in Recipe` ;

CREATE TABLE IF NOT EXISTS `Used in Recipe` (
  `food_id` INT UNSIGNED NOT NULL,
  `recipe_id` INT UNSIGNED NOT NULL,
  `alternative` VARCHAR(100) NULL,
  INDEX `FK_USEDINRECIPE_FOOD_idx` (`food_id` ASC) VISIBLE,
  INDEX `FK_USEDINRECIPE_RECIPE_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `FK_USEDINRECIPE_FOOD`
    FOREIGN KEY (`food_id`)
    REFERENCES `Food` (`food_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_USEDINRECIPE_RECIPE`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `Recipe` (`recipe_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grocery List`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Grocery List` ;

CREATE TABLE IF NOT EXISTS `Grocery List` (
  `food_id` INT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  `priority_level` VARCHAR(15) NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  INDEX `FK_GROCERY_FOOD_idx` (`food_id` ASC) VISIBLE,
  INDEX `FK_GROCERY_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `FK_GROCERY_FOOD`
    FOREIGN KEY (`food_id`)
    REFERENCES `Food` (`food_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_GROCERY_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Food Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Food Inventory` ;

CREATE TABLE IF NOT EXISTS `Food Inventory` (
  `food_id` INT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  `expiration_date` DATE NULL,
  `status` VARCHAR(15) NOT NULL,
  INDEX `FK_INVENTORY_FOOD_idx` (`food_id` ASC) VISIBLE,
  INDEX `FK_INVENTORY_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `FK_INVENTORY_FOOD`
    FOREIGN KEY (`food_id`)
    REFERENCES `Food` (`food_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_INVENTORY_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Medication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Medication` ;

CREATE TABLE IF NOT EXISTS `Medication` (
  `medication_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `instructions` VARCHAR(300) NULL,
  `nutrition_id` INT UNSIGNED NULL,
  PRIMARY KEY (`medication_id`),
  UNIQUE INDEX `nutrition_id_UNIQUE` (`nutrition_id` ASC) VISIBLE,
  CONSTRAINT `UQ_MEDICATION_NUTRITION`
    FOREIGN KEY (`nutrition_id`)
    REFERENCES `Nutritional Information` (`nutrition_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Supplements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supplements` ;

CREATE TABLE IF NOT EXISTS `Supplements` (
  `supplement_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `nutrition_id` INT UNSIGNED NULL,
  `brand` VARCHAR(30) NULL,
  UNIQUE INDEX `nutrition_id_UNIQUE` (`nutrition_id` ASC) VISIBLE,
  PRIMARY KEY (`supplement_id`),
  CONSTRAINT `UQ_SUPPLEMENTS_NUTRITION`
    FOREIGN KEY (`nutrition_id`)
    REFERENCES `Nutritional Information` (`nutrition_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diet Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Diet Log` ;

CREATE TABLE IF NOT EXISTS `Diet Log` (
  `account_id` INT UNSIGNED NOT NULL,
  `food_id` INT UNSIGNED NULL,
  `supplement_id` INT UNSIGNED NULL,
  `medication_id` INT UNSIGNED NULL,
  `recipe_id` INT UNSIGNED NULL,
  `entity_type` VARCHAR(10) NOT NULL,
  `time_entered` DATETIME NOT NULL,
  `serving_amount` DECIMAL(8,5) NULL,
  `meal_type` VARCHAR(9) NOT NULL,
  INDEX `FK_DIETLOG_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  INDEX `FK_DIETLOG_FOOD_idx` (`food_id` ASC) VISIBLE,
  INDEX `FK_DIETLOG_RECIPE_idx` (`recipe_id` ASC) VISIBLE,
  INDEX `FK_DIETLOG_SUPPLEMENTS_idx` (`supplement_id` ASC) VISIBLE,
  INDEX `FK_DIETLOG_MEDICATION_idx` (`medication_id` ASC) VISIBLE,
  CONSTRAINT `FK_DIETLOG_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_DIETLOG_FOOD`
    FOREIGN KEY (`food_id`)
    REFERENCES `Food` (`food_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_DIETLOG_RECIPE`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `Recipe` (`recipe_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_DIETLOG_SUPPLEMENTS`
    FOREIGN KEY (`supplement_id`)
    REFERENCES `Supplements` (`supplement_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_DIETLOG_MEDICATION`
    FOREIGN KEY (`medication_id`)
    REFERENCES `Medication` (`medication_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Saved Recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Saved Recipes` ;

CREATE TABLE IF NOT EXISTS `Saved Recipes` (
  `recipe_id` INT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  `bookmark_name` VARCHAR(30) NULL,
  INDEX `FK_SAVEDRECIPE_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  INDEX `FK_SAVEDRECIPE_RECIPE_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `FK_SAVEDRECIPE_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SAVEDRECIPE_RECIPE`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `Recipe` (`recipe_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meal Plans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Meal Plans` ;

CREATE TABLE IF NOT EXISTS `Meal Plans` (
  `meal_plan_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `meal_plan_name` VARCHAR(50) NOT NULL,
  `meal_plan_description` VARCHAR(1200) NOT NULL,
  PRIMARY KEY (`meal_plan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Followed Meal Plans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Followed Meal Plans` ;

CREATE TABLE IF NOT EXISTS `Followed Meal Plans` (
  `account_id` INT UNSIGNED NOT NULL,
  `meal_plan_id` SMALLINT UNSIGNED NOT NULL,
  `date_subscribed` DATE NOT NULL,
  INDEX `FK_FOLLOWEDMP_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  INDEX `FK_FOLLOWEDMP_MEALPLAN_idx` (`meal_plan_id` ASC) VISIBLE,
  CONSTRAINT `FK_FOLLOWEDMP_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_FOLLOWEDMP_MEALPLAN`
    FOREIGN KEY (`meal_plan_id`)
    REFERENCES `Meal Plans` (`meal_plan_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meal Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Meal Category` ;

CREATE TABLE IF NOT EXISTS `Meal Category` (
  `meal_category_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `meal_category_name` VARCHAR(35) NOT NULL,
  `meal_category_description` VARCHAR(120) NULL,
  PRIMARY KEY (`meal_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Recipe Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recipe Tags` ;

CREATE TABLE IF NOT EXISTS `Recipe Tags` (
  `meal_category_id` SMALLINT UNSIGNED NOT NULL,
  `recipe_id` INT UNSIGNED NOT NULL,
  `date_updated` DATE NOT NULL,
  INDEX `FK_RECIPETAGS_CATEGORY_idx` (`meal_category_id` ASC) VISIBLE,
  INDEX `FK_RECIPETAGS_RECIPE_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `FK_RECIPETAGS_CATEGORY`
    FOREIGN KEY (`meal_category_id`)
    REFERENCES `Meal Category` (`meal_category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RECIPETAGS_RECIPE`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `Recipe` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exercises` ;

CREATE TABLE IF NOT EXISTS `Exercises` (
  `exercise_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `exercise_name` VARCHAR(60) NOT NULL,
  `exercise_description` VARCHAR(120) NULL,
  `calories_burned` SMALLINT UNSIGNED NOT NULL,
  `time` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`exercise_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercise Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exercise Log` ;

CREATE TABLE IF NOT EXISTS `Exercise Log` (
  `exercise_id` INT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  `date_entered` DATETIME NOT NULL,
  `time_taken` SMALLINT UNSIGNED NOT NULL,
  INDEX `FK_EXERCISELOG_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  INDEX `FK_EXERCISELOG_EXERCISE_idx` (`exercise_id` ASC) VISIBLE,
  CONSTRAINT `FK_EXERCISELOG_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_EXERCISELOG_EXERCISE`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `Exercises` (`exercise_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Groups` ;

CREATE TABLE IF NOT EXISTS `Groups` (
  `group_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(50) NOT NULL,
  `group_description` VARCHAR(500) NULL,
  `date_created` DATE NOT NULL,
  `group_type` VARCHAR(20) NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Joined Groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Joined Groups` ;

CREATE TABLE IF NOT EXISTS `Joined Groups` (
  `account_id` INT UNSIGNED NOT NULL,
  `group_id` SMALLINT UNSIGNED NOT NULL,
  `date_joined_group` DATE NOT NULL,
  INDEX `FK_JOINEDGROUP_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  INDEX `FK_JOINEDGROUP_GROUP_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `FK_JOINEDGROUP_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_JOINEDGROUP_GROUP`
    FOREIGN KEY (`group_id`)
    REFERENCES `Groups` (`group_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Posts` ;

CREATE TABLE IF NOT EXISTS `Posts` (
  `post_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NULL,
  `post_title` VARCHAR(45) NOT NULL,
  `post_description` VARCHAR(1000) NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `FK_POSTS_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `FK_POSTS_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Notification` ;

CREATE TABLE IF NOT EXISTS `Notification` (
  `notification_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  `notification_description` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`notification_id`),
  INDEX `FK_NOTIFICATION_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `FK_NOTIFICATION_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Challenges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Challenges` ;

CREATE TABLE IF NOT EXISTS `Challenges` (
  `challenge_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `challenge_name` VARCHAR(30) NOT NULL,
  `challenge_description` VARCHAR(120) NULL,
  `challenge_length` TINYINT NULL,
  `challenge_type` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`challenge_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Accepted Challenges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Accepted Challenges` ;

CREATE TABLE IF NOT EXISTS `Accepted Challenges` (
  `challenge_id` SMALLINT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  `date_started` DATE NOT NULL,
  `date_ended` DATE NULL,
  INDEX `FK_ACCEPTEDCHALLENGES_CHALLENGE_idx` (`challenge_id` ASC) VISIBLE,
  INDEX `FK_ACCEPTEDCHALLENGES_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `FK_ACCEPTEDCHALLENGES_CHALLENGE`
    FOREIGN KEY (`challenge_id`)
    REFERENCES `Challenges` (`challenge_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ACCEPTEDCHALLENGES_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Friends` ;

CREATE TABLE IF NOT EXISTS `Friends` (
  `sender_id` INT UNSIGNED NOT NULL,
  `receiver_id` INT UNSIGNED NOT NULL,
  `favorite` TINYINT NOT NULL,
  INDEX `FK_FRIENDS_SENDERACCOUNT_idx` (`sender_id` ASC) VISIBLE,
  INDEX `FK_FRIENDS_RECIEVERACCOUNT_idx` (`receiver_id` ASC) VISIBLE,
  CONSTRAINT `FK_FRIENDS_SENDERACCOUNT`
    FOREIGN KEY (`sender_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_FRIENDS_RECEIVERACCOUNT`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `General User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `General User` ;

CREATE TABLE IF NOT EXISTS `General User` (
  `account_id` INT UNSIGNED NOT NULL,
  `date_joined` DATE NOT NULL,
  `role` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`account_id`),
  CONSTRAINT `PK_GENERAL_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Admin` ;

CREATE TABLE IF NOT EXISTS `Admin` (
  `account_id` INT UNSIGNED NOT NULL,
  `date_joined` DATE NOT NULL,
  `role` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`account_id`),
  CONSTRAINT `PK_ADMIN_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Day Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Day Log` ;

CREATE TABLE IF NOT EXISTS `Day Log` (
  `account_id` INT UNSIGNED NOT NULL,
  `calories_consumed` SMALLINT UNSIGNED NOT NULL,
  `calories_burned` SMALLINT UNSIGNED NOT NULL,
  `calories_status` VARCHAR(11) NOT NULL,
  `date` DATE NOT NULL,
  `protein` DECIMAL(4,1) NOT NULL,
  `carbs` DECIMAL(4,1) NOT NULL,
  `fats` DECIMAL(4,1) NOT NULL,
  INDEX `FK_DAYLOG_ACCOUNT_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `FK_DAYLOG_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account Roles` ;

CREATE TABLE IF NOT EXISTS `Account Roles` (
  `account_id` INT UNSIGNED NOT NULL,
  `date_joined` DATE NOT NULL,
  `role` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`account_id`),
  CONSTRAINT `FK_ROLES_ACCOUNT`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
